### ISSUE TITLE
Unable to mount nfs volume in docker compose (vagrant) 

### ISSUE THREAD

**Issue by abhaynahar** [hashicorp/vagrant#10798]
Vagrant 2.2.0
### Host operating system
MacOs Mojave 10.14.2

### Vagrantfile
```
Vagrant.configure(2) do |config|
config.vm.define "iceland" do |iceland|
    iceland.vm.provider "docker" do |docker|
      docker.build_dir = "/iceland/server/vagrant"
      docker.create_args = ["--add-host=iceland:127.0.0.1"]
      docker.name = "iceland"
      docker.compose=true
      docker.compose_configuration={
          "volumes" => {
              'iceland_data_volume' => {
                  "driver" => "local",
                  "driver_opts" => {
                      "type" => "nfs",
                      "o" => "addr=host.docker.internal,nolock",
                      "device" => ":/iceland/data"
                  }
              }
          },
      }
      docker.volumes =['iceland_data_volume:/temp_directory/data']
      docker.ports =
          [
              "1000:1000",
          ]
    end
  end
  end
```
### Dockerfile in the build_dir
```FROM ubuntu:18.04```

### Expected behavior
Running vagrant up should have generated a docker-compose.yml that looks like this 
```---
version: '2'
volumes:
  iceland_data_volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,nolock
      device: ":/iceland/data"
services:
  iceland:
    build:
      context: "/iceland/server/vagrant/"
    environment: {}
    expose: []
    ports:
    - 1000:1000
    volumes:
    - "iceland_data_volume:/temp_directory/data"
    - "/iceland/server/vagrant:/vagrant"
    links: []
    command: []
```

### Actual behavior
What actually happened?
```
---
version: '2'
volumes:
  iceland_data_volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,nolock
      device: ":/iceland/data"
services:
  iceland:
    build:
      context: "/iceland/server/vagrant"
    environment: {}
    expose: []
    ports:
    - 1000:1000
    volumes:
    - "/iceland/server/vagrant/iceland_data_volume:/temp_directory/data"
    - "/iceland/server/vagrant:/vagrant"
    links: []
    command: []
```
### Steps to reproduce
Use the above vagrant and docker (vagrant up) file to generate the following docker-compose.yml inside of `.vagrant/docker-compose` directory

### The bug
volumes explicitly created in docker compose are appended with the current path 
`"/iceland/server/vagrant/iceland_data_volume:/temp_directory/data" ` where as in my case it should have been only `"iceland_data_volume:/temp_directory/data"` where `iceland_data_volume` is a nfs volume.
This behaviour is happening because of https://github.com/hashicorp/vagrant/blob/85acf0cac724ef4bfda593a66e0c17f7e4110da0/plugins/providers/docker/driver/compose.rb#L105 line of code I think.
