### ISSUE TITLE
building with compose does not pass build args

### ISSUE THREAD

**Issue by florianschoen** [hashicorp/vagrant#10959]
### Vagrant version
Vagrant 2.2.5

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = Dir.pwd
    d.compose = true
    d.build_args = {
      "foo" => "bar"
    }
  end
end
```
### Dockerfile
```
FROM debian:latest
CMD [ '/bin/bash' ]
```

### Expected behavior
Create a compose file containing build args
example:
```yml
---
version: '2'
services:
  default:
    build:
      context: "/home/schoen/tmp/vagrant-bug"
      args:
        foo: bar
    environment: {}
    expose: []
    ports: []
    volumes:
    - "/home/schoen/tmp/vagrant-bug:/vagrant"
    links: []
    command: []
```

### Actual behavior
Compose file does not contain build args
```yml
---
version: '2'
services:
  default:
    build:
      context: "/home/schoen/tmp/vagrant-bug"
    environment: {}
    expose: []
    ports: []
    volumes:
    - "/home/schoen/tmp/vagrant-bug:/vagrant"
    links: []
    command: []
```

### Steps to reproduce
1. copy vagrantfile and dockerfile
2. vagrant up
3. cat .vagrant/docker-compose/docker-compose.yml
