### ISSUE TITLE
vagrant vm compose mount data for postgres error

### ISSUE THREAD

**Issue by moluzhui** [hashicorp/vagrant#11107]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
`vagrant 2.0.2`

### Host operating system
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```
### Guest operating system
```
node_conf.vm.box = "chaifeng/ubuntu-16.04-docker-18.09"
node_conf.vm.box_version = "201812.27.0"
```

### Vagrantfile
Part of the code is as follows
```ruby
config.vm.define :"vm1" do |node_conf|
    node_conf.vm.synced_folder ".", "/home/vagrant/code" ,mount_options:["dmode=777","fmode=777"]
    node_conf.vm.box = "chaifeng/ubuntu-16.04-docker-18.09"
    node_conf.vm.box_version = "201812.27.0"
    node_conf.vm.box_check_update = false
```
> File permissions are fully enabled because of the error reported earlier: initdb: could not create directory "/var/lib/postgresql/data/pg_wal": Permission denied

### Compose file
Part of the code is as follows
```
db:
    image: postgres:11.4
    container_name:Postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - $PWD/module/postgresData:/var/lib/postgresql/data
      - $PWD/module/postgresinit/:/docker-entrypoint-initdb.d/
      - $PWD/module/postgresbackup/:/tmp/
    ports:
      - "5432:5432"
```

### Expected behavior
What should have happened?

When I type `docker-compose up`, The service should start successfully

### Actual behavior
What actually happened?

when type `docker-compose up`, postgres container error is as follows
```
Postgres    | The files belonging to this database system will be owned by user "postgres".
Postgres    | This user must also own the server process.
Postgres    | 
Postgres    | The database cluster will be initialized with locale "en_US.utf8".
Postgres    | The default database encoding has accordingly been set to "UTF8".
Postgres    | The default text search configuration will be set to "english".
Postgres    | 
Postgres    | Data page checksums are disabled.
Postgres    | 
Postgres    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
Postgres    | creating subdirectories ... ok
Postgres    | selecting default max_connections ... 20
Postgres    | selecting default shared_buffers ... 400kB
Postgres    | selecting default timezone ... Etc/UTC
Postgres    | selecting dynamic shared memory implementation ... posix
Postgres    | creating configuration files ... ok
Postgres    | running bootstrap script ... 2019-10-08 09:05:21.290 UTC [78] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
Postgres    | 2019-10-08 09:05:21.290 UTC [78] HINT:  The server must be started by the user that owns the data directory.
Postgres    | child process exited with exit code 1
Postgres    | initdb: removing contents of data directory "/var/lib/postgresql/data"
Postgres exited with code 1
```

### Problem
What caused this situation and how to solve it?
