### ISSUE TITLE
[Question] vagrant and ansible inventory

### ISSUE THREAD

**Issue by moleszek** [hashicorp/vagrant#11458]
Hi, 
I have a question because I can't find the answer.
Can vagrant and ansible share an IP address between their inventory?

on vagrant I have ***node.yaml***
```
- hostname: "test"
  IP: 192.168.0.1
```
on ansible I have *inventory.yml*
```
all:
  children:
      Linux:
        vars:
          ansible_user: root
          ansible_ssh_pass: vagrant
        children:
          cassandra:
            hosts:
              192.168.0.1:
```
Is there any option to pass a variable to ansible inventory to use IP from vagrant ***node.yaml*** or the opposite way, vagrant use IP from ansible inventory in their ***.yaml*** file?

Or, I ***ansible.groups*** can be configured in different file
e.g. 
***config_groups.rb***
```
CASSANDRA_CON {
IP: 192.168.0.1,
IP: 192.168.0.2
}
```

and the ansible.groups looks like 
```
ansible.groups = {
   "cassandra" => "CASSANDRA_CON"
}
