### ISSUE TITLE
vagrant ansible galaxy does not support git/github

### ISSUE THREAD

**Issue by nhojpatrick** [hashicorp/vagrant#11501]
### Vagrant version
Vagrant 2.2.7

### Host operating system

Mac 10.15.4

### Guest operating system

centos/7

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.memory = 1536
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end
  config.vm.define "vmname", autostart: true do |inst|
    inst.vm.hostname = "vmname"
    inst.vm.provision :ansible_local do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "provisioning/fix.yaml"
    end
    inst.vm.provision :ansible_local do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.galaxy_role_file = 'provisioning/requirements.yaml'
      ansible.galaxy_roles_path = '/home/vagrant/.ansible/roles'
      ansible.galaxy_command = 'ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path}'
      ansible.playbook = "provisioning/playbook.yaml"
    end
  end
end
```

fix.yaml
```yaml
- name: fix
  hosts: all
  become: true
  tasks:
    - name: Ensure git installed for ansible-galazy github support
      yum:
        name: "git"
        state: latest
```

requirements.yaml
```yaml
- name: "galaxy.role"
  src: https://github.com/user/project
  version: branch
```
requirements.yaml (previous version)
```yaml
- src: galaxy.role
```

playbook.yaml
```yaml
- name: playbook
  hosts: all
  become: true
  roles:
    - role: galaxy.role
````

### Debug output

```console
==> vmhost: Running provisioner: ansible_local...
    vmhost: Running ansible-galaxy...
[WARNING]: - galaxy.role was NOT installed successfully: could not
find/use git, it is required to continue with installing
https://github.com/user/project
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### Expected behavior

Using ansible galaxy roles works fine, but discovered a bug in published galaxy role. So created branch with fix and wanted to test that role from a github project on a specific branch. So changed the requirements file so override the name and use a url of github and version of the branch i wanted to test.

I then wanted to simply do `vagrant destroy -f && time vagrant up` to check everything now passed.

I would not expect to have to manually install git, maybe if galaxy is used then git is automatically installed, or somehow scan requirements yaml specified and determine if git support is needed.

### Actual behavior

Had to add new ansible_local before hand that installs git before ansible_local galaxy is executed.

### Steps to reproduce

1. vagrant up using the Vagrantfile above, galaxy role is for oracle weblogic which required ~1GB zip so change to a more simply galaxy role in github.
2.
3.

### References

Have search issues for anything relevant and not discovered any.
n/a
