### ISSUE TITLE
Unexpected ansible-playbook command line

### ISSUE THREAD

**Issue by promethe42** [hashicorp/vagrant#11776]
### Vagrant version

```bash
$ vagrant -v
Vagrant 2.2.9
```

### Host operating system

Ubuntu 20.04

### Guest operating system

Ubuntu 18.04

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.2.9"

Vagrant.configure("2") do |config|
  config.vagrant.plugins = {
    "vagrant-env" => { "version" => "0.0.3" },
    "vagrant-disksize" => { "version" => "0.1.3" },
  }

  config.vm.define "git" do |host|
    host.vm.box = "ubuntu/bionic64"
    host.vm.hostname = "git.aerys.in.test"
    host.vm.network :private_network, ip: "192.168.42.2"

    host.env.enable
    
    host.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end

    host.vm.provision "git", type: "ansible_local" do |ansible|
      ansible.version = "2.8.0"
      ansible.install_mode = "pip"
      ansible.playbook = "provisioning/playbook.yml"
      ansible.verbose = 'v'
      ansible.inventory_path = "provisioning/hosts.yml"
      ansible.become = true
      ansible.skip_tags = ["dcl2gitlab"],
      ansible.extra_vars = {
        ansible_ssh_user: "vagrant",
      }
    end
end
```

### Debug output

[vagrant_provision_git.txt](https://github.com/hashicorp/vagrant/files/4939037/vagrant_provision_git.txt)

### Expected behavior

The `ansible-playbook` command line should be:

```bash
cd /vagrant && PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook --connection="local" --limit="git" --inventory-file=provisioning/hosts.yml --extra-vars=\{\"base_hostname\":\"aerys.in.test\",\"ansible_ssh_user\":\"vagrant\"\} --become -v --skip-tags=dcl2gitlab provisioning/playbook.yml
```

### Actual behavior

```bash
$ vagrant provision git
==> git: Running provisioner: git (ansible_local)...
    git: Running ansible-playbook...
cd /vagrant && PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook --limit="git" --inventory-file=provisioning/hosts.yml --extra-vars=\{\"base_hostname\":\"aerys.in.test\",\"ansible_ssh_user\":\"vagrant\"\} --become -v --skip-tags=dcl2gitlab,{:base_hostname=>"aerys.in.test", :ansible_ssh_user=>"vagrant"} provisioning/playbook.yml
ERROR! the playbook: :ansible_ssh_user= could not be found
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Please note how:

* `--skip-tags=dcl2gitlab` is not concatenated to anything else
* `--connection="local"` has been added

### Steps to reproduce

1. `vagrant up git` with the provided Vagrantfile

### References

None AFAIK.

**Comment by promethe42** [comment]
If I remove:

```ruby
      ansible.skip_tags = ["dcl2gitlab"],
```

then the command line is valid:

```bash
==> git: Running provisioner: git (ansible_local)...
    git: Running ansible-playbook...
cd /vagrant && PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook --limit="git" --inventory-file=provisioning/hosts.yml --extra-vars=\{\"base_hostname\":\"aerys.in.test\",\"ansible_ssh_user\":\"vagrant\"\} --become -v provisioning/playbook.yml
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to 
allow bad characters in group names by default, this will change, but still be 
user configurable on deprecation. This feature will be removed in version 2.10.
 Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
 [WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details


PLAY [server:&linux] ***********************************************************

TASK [Gathering Facts] *********************************************************
fatal: [git]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Host key verification failed.", "unreachable": true}

PLAY RECAP *********************************************************************
git                        : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
```

but still doesn't work because Ansible won't connect. That's why `--connection=local` must be added in `ansible.raw_arguments`. Which is unexpected for the `ansible_local` provisioner.

**Comment by gildegoma** [comment]
Hi @promethe42. Thank you for asking... this doesn't seem to be any vagrant bug, but I'd be happy to help you to fix your settings.

A few remarks and questions about the provided information:

1. The line `ansible.skip_tags = ["dcl2gitlab"],` ends with a comma (`,`) which doesn't make sense, and apparently leads to pick the rest of the provisioner ruby-block and append it to the `--skip-tags` argument (see debug output: `--skip-tags=dcl2gitlab,{:base_hostname=>"aerys.in.test", :ansible_ssh_user=>"vagrant"}`). Please just try to add back `ansible.skip_tags = ["dcl2gitlab"]`, it should work as good as when you removed this line (second comment).
1. I don't get why you declare a `extra_vars = { ansible_ssh_user: "vagrant" }` when using the `ansible_local` provisioner. Do you want to configure your `git` VM with Ansible, or configure other targets from the `git` machine?
1. could you please give the content of your `provisioning/hosts.yml` inventory (or even better a complete github repo with your example and a description of what you want to achieve.

Thank you very much!

**Comment by promethe42** [comment]
Oh boy... this is awkward... :blush: 

> The line ansible.skip_tags = ["dcl2gitlab"], ends with a comma (,) which doesn't make sense, and apparently leads to pick the rest of the provisioner ruby-block and append it to the --skip-tags argument (see debug output: --skip-tags=dcl2gitlab,{:base_hostname=>"aerys.in.test", :ansible_ssh_user=>"vagrant"}). Please just try to add back ansible.skip_tags = ["dcl2gitlab"], it should work as good as when you removed this line (second comment).

Totally got caught off guard by the trailing-coma-so-I-don't-get-git-diff-for-nothing habit.

I really never though this would be valid Ruby syntax... That is indeed the problem.

> I don't get why you declare a extra_vars = { ansible_ssh_user: "vagrant" } when using the ansible_local provisioner. Do you want to configure your git VM with Ansible, or configure other targets from the git machine?

Kinda didn't matter at the time since it didn't get to that point. I removed it in the meantime. It is indeed not required.

> could you please give the content of your provisioning/hosts.yml inventory (or even better a complete github repo with your example and a description of what you want to achieve.

Here you go:

```yaml
all:
  hosts:
    git:
      ansible_host: "git.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'GIT_AERYS_IN_SSH_KEY') }}"
      ansible_ssh_user: aerys
      ansible_become: yes
    monitoring:
      ansible_host: "monitoring.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'GIT_AERYS_IN_SSH_KEY') }}"
      ansible_ssh_user: aerys
      ansible_become: yes
    prometheus:
      ansible_host: "prometheus.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'GIT_AERYS_IN_SSH_KEY') }}"
      ansible_ssh_user: aerys
      ansible_become: yes
    registry:
      ansible_host: "registry.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'GIT_AERYS_IN_SSH_KEY') }}"
      ansible_ssh_user: aerys
      ansible_become: yes
    team:
      ansible_host: "team.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'GIT_AERYS_IN_SSH_KEY') }}"
      ansible_ssh_user: aerys
      ansible_become: yes
    build-linux:
      ansible_host: "build-linux.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'BUILD_LINUX_AERYS_IN_SSH_KEY') }}"
      ansible_ssh_user: aerys
      ansible_become: yes
    build-windows:
      ansible_host: "build-windows.{{ base_hostname }}"
      ansible_user: root
      ansible_password: "{{ lookup('env', 'BUILD_WINDOWS_AERYS_IN_PASSWORD' )}}"
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_operation_timeout_sec: 500
      ansible_winrm_read_timeout_sec: 600
    vpn:
      ansible_host: "vpn.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'VPN_AERYS_IN_SSH_KEY') }}"
      ansible_ssh_user: ubuntu
      ansible_become: yes
      vpn_ip: 10.1.0.1/32
```

I guess the `--connection=local` is required because the `ansible_local` provisioner does not expect `ansible_host` to be set in the host_vars. But that value does match with the Vagrant VM hostname though (`git.aerys.in.test` in this case...).
