### ISSUE TITLE
When I run kitchen ci with multiple vagrants instance, I got Error the machine is in the 'unknown' state.  

### ISSUE THREAD

**Issue by LyTuan** [hashicorp/vagrant#11919]
### Vagrant version
Vagrant 2.2.10

### Host operating system
I run this test in a `virtual machine windows 10`

### Guest operating system
- window 2012 r2
- ubuntu 18.04

 
### Vagrantfile
This is two Vagrantfiles:
```
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "win2k12r2"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "E:/cym-auto-test-agent/files", "/home/vagrant/files", nil
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-cym-auto-test-agent-uninstallation-win-win2k12r2-ba92679d-e476-4b62-b597-a79a1e772e1c"
    p.gui = true
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end


```

```
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "ubuntu-18.04"
  c.vm.hostname = "uninstallation-linux-ubuntu-1804.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "E:/cym-auto-test-agent/files", "/home/vagrant/files", nil
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-cym-auto-test-agent-uninstallation-linux-ubuntu-1804-504933a3-c7db-475e-92cc-80088f6d02f4"
    p.gui = true
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end

```

### Debug output

```
       The guest machine entered an invalid state while waiting for it
       to boot. Valid states are 'starting, running'. The machine is in the
       'unknown' state. Please verify everything is configured
       properly and try again.
       
       If the provider you're using has a GUI that comes with it,
       it is often helpful to open that and watch the machine, since the
       GUI often has more helpful error messages than Vagrant can retrieve.
       For example, if you're using VirtualBox, run `vagrant up` while the
       VirtualBox GUI is open.
       
       The primary issue for this error is that the provider you're using
       is not properly configured. This is very rarely a Vagrant issue.
```

### Expected behavior

```
Vagrant instance <installation-linux-ubuntu-1804> created.

```

### Actual behavior

What actually happened?

### Steps to reproduce
I use kitchen ci automation test with driver vagrant
1. I have .kitchen.yml like this:
```
---
driver:
  name: vagrant
  synced_folders:
   - ['./files', '/home/vagrant/files']
verifier:
   name: inspec

platforms:
  - name: win2k12r2
    driver:
      box: win2k12r2
      gui: true

  - name: ubuntu-18.04
    driver:
      box: ubuntu-18.04
      gui: true
    transport:
      connection_retries: 20
      max_wait_until_ready: 600
suites:
  - name: installation_win
    provisioner:
        name: shell
        script: 'scripts/install.ps1'
    verifier:
      inspec_tests:
        - test/integration/installation
      reporter:
       - html:report/%{platform}_%{suite}_install_report.html
       - json:report/%{platform}_%{suite}_install_report.json
    excludes:
        - ubuntu-18.04
  - name: installation_linux
    provisioner:
        name: shell
        script: 'scripts/install.sh'
    verifier:
      inspec_tests:
        - test/integration/installation
      reporter:
        - html:report/%{platform}_%{suite}_install_report.html
        - json:report/%{platform}_%{suite}_install_report.json
    excludes:
        - win2k12r2
  - name: uninstallation_linux
    provisioner:
      name: shell
      script: 'scripts/uninstall.sh'
    verifier:
      inspec_tests:
         - test/integration/uninstallation
      reporter:
         - html:report/%{platform}_%{suite}_uninstall_report.html
         - json:report/%{platform}_%{suite}_uninstall_report.json
    excludes:
      - win2k12r2
  - name: uninstallation_win
    provisioner:
      name: shell
      script: 'scripts/uninstall.ps1'
    verifier:
      inspec_tests:
        - test/integration/uninstallation
      reporter:
        - html:report/%{platform}_%{suite}_uninstall_report.html
        - json:report/%{platform}_%{suite}_uninstall_report.json
    excludes:
      - ubuntu-18.04
```
2.  Run `kitchen test`
3. When multiple instance vagrant run, I got the above error!

Are there any other GitHub issues (open or closed) that should be linked here?
-  https://github.com/hashicorp/vagrant/issues/5646
