### ISSUE TITLE
Vagrant tries to install epel for amazon linux2 b

### ISSUE THREAD

**Issue by mykelalvis** [hashicorp/vagrant#12110]
### Vagrant version
```
❯ vagrant -v
Vagrant 2.2.14
```

### Host operating system
```
❯ uname -a
Linux ********.org 5.9.13-200.fc33.x86_64 #1 SMP Tue Dec 8 15:42:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
### Guest operating system
`  config.vm.box = "bento/amazonlinux-2"`

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "centos/8"
  config.vm.box = "bento/amazonlinux-2"
  config.vm.network "forwarded_port", guest: 8080, host: 18080
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  # An easy package update
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo yum -y update
  # SHELL

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = true
  end
end
```

#### playbook.yml
```yaml

---
# 
- name: 'Configure this server'
  hosts: default
  become: true
  handlers:
    - name: restart_service
      service: 
        name: service
        state: restarted
        
  tasks:
    - name: Install Sudo
      package:
        name: sudo
        state: latest

```

### Debug output

[link to a GitHub Gist containing the complete debug output](https://gist.github.com/mykelalvis/3a6cd806dabe4007fa5cfd458aec186e)

### Expected behavior

Expected `ansible_local` to install Ansible and then execute playbook

### Actual behavior

Vagrant appeared to 404 trying to install EPEL

### Steps to reproduce

1. Put `Vagrantfile` and `jenkins.yml` into local directory
2. `vagrant up`
3. Attempt to reconcile your life choices with what you actually wanted and then become despondent about the inevitable heat death of the universe.
