### ISSUE TITLE
Powershell tests not working in Fedora

### ISSUE THREAD

**Issue by pvalena** [hashicorp/vagrant#12363]
### Vagrant version

2.2.16

### Host operating system

Fedora, during build phase (not yet released).

### Guest operating system

**-**
I'm getting the error while running tests.

### Actual behavior

```
  3) Vagrant::Util::PowerShell.execute should validate installation before use
     Failure/Error: result.stdout.gsub("\"", "").strip if result.exit_code == 0

     NoMethodError:
       undefined method `exit_code' for nil:NilClass
     # ./lib/vagrant/util/powershell.rb:41:in `block in executable'
     # ./lib/vagrant/util/powershell.rb:39:in `map'
     # ./lib/vagrant/util/powershell.rb:39:in `executable'
     # ./lib/vagrant/util/powershell.rb:87:in `execute'
     # ./test/unit/vagrant/util/powershell_test.rb:122:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  4) Vagrant::Util::PowerShell.execute should include command to execute
     Failure/Error: expect(comm.to_s).to include("custom-command")
       expected "" to include "custom-command"
     # ./test/unit/vagrant/util/powershell_test.rb:128:in `block (4 levels) in <top (required)>'
     # ./lib/vagrant/util/powershell.rb:40:in `block in executable'
     # ./lib/vagrant/util/powershell.rb:39:in `map'
     # ./lib/vagrant/util/powershell.rb:39:in `executable'
     # ./lib/vagrant/util/powershell.rb:87:in `execute'
     # ./test/unit/vagrant/util/powershell_test.rb:130:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  5) Vagrant::Util::PowerShell.execute should accept custom environment
     Failure/Error: expect(comm.to_s).to include("$env:TEST_KEY=test-value")
       expected "" to include "$env:TEST_KEY=test-value"
     # ./test/unit/vagrant/util/powershell_test.rb:136:in `block (4 levels) in <top (required)>'
     # ./lib/vagrant/util/powershell.rb:40:in `block in executable'
     # ./lib/vagrant/util/powershell.rb:39:in `map'
     # ./lib/vagrant/util/powershell.rb:39:in `executable'
     # ./lib/vagrant/util/powershell.rb:87:in `execute'
     # ./test/unit/vagrant/util/powershell_test.rb:138:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  6) Vagrant::Util::PowerShell.execute should define a custom module path
     Failure/Error: expect(comm.to_s).to include("$env:PSModulePath+';C:\\My-Path'")
       expected "" to include "$env:PSModulePath+';C:\\My-Path'"
     # ./test/unit/vagrant/util/powershell_test.rb:144:in `block (4 levels) in <top (required)>'
     # ./lib/vagrant/util/powershell.rb:40:in `block in executable'
     # ./lib/vagrant/util/powershell.rb:39:in `map'
     # ./lib/vagrant/util/powershell.rb:39:in `executable'
     # ./lib/vagrant/util/powershell.rb:87:in `execute'
     # ./test/unit/vagrant/util/powershell_test.rb:146:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  7) Vagrant::Util::PowerShell.execute_cmd should include command to execute
     Failure/Error: expect(comm.to_s).to include("custom-command")
       expected "" to include "custom-command"
     # ./test/unit/vagrant/util/powershell_test.rb:172:in `block (4 levels) in <top (required)>'
     # ./lib/vagrant/util/powershell.rb:40:in `block in executable'
     # ./lib/vagrant/util/powershell.rb:39:in `map'
     # ./lib/vagrant/util/powershell.rb:39:in `executable'
     # ./lib/vagrant/util/powershell.rb:122:in `execute_cmd'
     # ./test/unit/vagrant/util/powershell_test.rb:175:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  8) Vagrant::Util::PowerShell.execute_cmd should accept custom environment
     Failure/Error: expect(comm.to_s).to include("$env:TEST_KEY=test-value")
       expected "" to include "$env:TEST_KEY=test-value"
     # ./test/unit/vagrant/util/powershell_test.rb:181:in `block (4 levels) in <top (required)>'
     # ./lib/vagrant/util/powershell.rb:40:in `block in executable'
     # ./lib/vagrant/util/powershell.rb:39:in `map'
     # ./lib/vagrant/util/powershell.rb:39:in `executable'
     # ./lib/vagrant/util/powershell.rb:122:in `execute_cmd'
     # ./test/unit/vagrant/util/powershell_test.rb:184:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  9) Vagrant::Util::PowerShell.execute_cmd should define a custom module path
     Failure/Error: expect(comm.to_s).to include("$env:PSModulePath+';C:\\My-Path'")
       expected "" to include "$env:PSModulePath+';C:\\My-Path'"
     # ./test/unit/vagrant/util/powershell_test.rb:190:in `block (4 levels) in <top (required)>'
     # ./lib/vagrant/util/powershell.rb:40:in `block in executable'
     # ./lib/vagrant/util/powershell.rb:39:in `map'
     # ./lib/vagrant/util/powershell.rb:39:in `executable'
     # ./lib/vagrant/util/powershell.rb:122:in `execute_cmd'
     # ./test/unit/vagrant/util/powershell_test.rb:193:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  10) Vagrant::Util::PowerShell.execute_inline should include command to execute
      Failure/Error: expect(comm.to_s).to include("custom-command")
        expected "" to include "custom-command"
      # ./test/unit/vagrant/util/powershell_test.rb:236:in `block (4 levels) in <top (required)>'
      # ./lib/vagrant/util/powershell.rb:40:in `block in executable'
      # ./lib/vagrant/util/powershell.rb:39:in `map'
      # ./lib/vagrant/util/powershell.rb:39:in `executable'
      # ./lib/vagrant/util/powershell.rb:156:in `execute_inline'
      # ./test/unit/vagrant/util/powershell_test.rb:239:in `block (3 levels) in <top (required)>'
      # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  11) Vagrant::Util::PowerShell.execute_inline should accept custom environment
      Failure/Error: expect(comm.to_s).to include("$env:TEST_KEY=test-value")
        expected "" to include "$env:TEST_KEY=test-value"
      # ./test/unit/vagrant/util/powershell_test.rb:245:in `block (4 levels) in <top (required)>'
      # ./lib/vagrant/util/powershell.rb:40:in `block in executable'
      # ./lib/vagrant/util/powershell.rb:39:in `map'
      # ./lib/vagrant/util/powershell.rb:39:in `executable'
      # ./lib/vagrant/util/powershell.rb:156:in `execute_inline'
      # ./test/unit/vagrant/util/powershell_test.rb:248:in `block (3 levels) in <top (required)>'
      # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  12) Vagrant::Util::PowerShell.execute_inline should define a custom module path
      Failure/Error: expect(comm.to_s).to include("$env:PSModulePath+';C:\\My-Path'")
        expected "" to include "$env:PSModulePath+';C:\\My-Path'"
      # ./test/unit/vagrant/util/powershell_test.rb:254:in `block (4 levels) in <top (required)>'
      # ./lib/vagrant/util/powershell.rb:40:in `block in executable'
      # ./lib/vagrant/util/powershell.rb:39:in `map'
      # ./lib/vagrant/util/powershell.rb:39:in `executable'
      # ./lib/vagrant/util/powershell.rb:156:in `execute_inline'
      # ./test/unit/vagrant/util/powershell_test.rb:257:in `block (3 levels) in <top (required)>'
      # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

### Steps to reproduce

1. Prepare installation of vagrant from source.
2. `$ rake -f tasks/test.rake test:unit`

### Additional information

We're using Ruby 3.0, so I've applied additional fixes. You can see the patches here:
  https://github.com/hashicorp/vagrant/pull/12273
  https://github.com/hashicorp/vagrant/pull/12353
  https://github.com/hashicorp/vagrant/pull/12352
