### ISSUE TITLE
Vagrant tests fails for `unix_mount_helpers_test.rb`

### ISSUE THREAD

**Issue by pvalena** [hashicorp/vagrant#12362]
### Vagrant version

2.2.16

### Host operating system

Fedora, during build phase (not yet released).

### Guest operating system

**-**
I'm getting the error while running tests.

### Actual behavior

```
  3) VagrantPlugins::SyncedFolder::UnixMountHelpers.merge_mount_options with no override should split options into individual options
     Failure/Error: @@logger = nil

     RuntimeError:
       class variable access from toplevel
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:10:in `block (3 levels) in <top (required)>'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:9:in `initialize'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:9:in `new'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:9:in `block (2 levels) in <top (required)>'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:22:in `block (4 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  4) VagrantPlugins::SyncedFolder::UnixMountHelpers.merge_mount_options with overrides should merge all options
     Failure/Error: @@logger = nil

     RuntimeError:
       class variable access from toplevel
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:10:in `block (3 levels) in <top (required)>'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:9:in `initialize'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:9:in `new'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:9:in `block (2 levels) in <top (required)>'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:29:in `block (4 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  5) VagrantPlugins::SyncedFolder::UnixMountHelpers.merge_mount_options with overrides should override options defined in base
     Failure/Error: @@logger = nil

     RuntimeError:
       class variable access from toplevel
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:10:in `block (3 levels) in <top (required)>'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:9:in `initialize'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:9:in `new'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:9:in `block (2 levels) in <top (required)>'
     # ./test/unit/plugins/synced_folders/unix_mount_helpers_test.rb:34:in `block (4 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

### Steps to reproduce

1. Prepare installation of vagrant from source.
2. `$ rake -f tasks/test.rake test:unit`

### Additional information

We're using Ruby 3.0, so I've applied additional fixes. You can see the patches here:
  https://github.com/hashicorp/vagrant/pull/12273
  https://github.com/hashicorp/vagrant/pull/12353
  https://github.com/hashicorp/vagrant/pull/12352
