### ISSUE TITLE
Could Vagrant possibly help look into this bug (on another repo, issue where Windows VM freezes during boot using Vagrant)

### ISSUE THREAD

**Issue by jt0dd** [hashicorp/vagrant#12743]
### Vagrant version

2.2.19

### Host operating system

Windows 11 Pro

### Guest operating system

Windows Server 2019

### Vagrantfile

Easily testable example, with virtualbox / Windows 10:

```
git clone https://github.com/Marshall-Hallenbeck/red_team_attack_lab
cd ./red_team_attack_lab
vagrant plugin install vagrant-hostmanager vagrant-vbguest
vagrant up
```

But as requested:

```ruby
# based on https://github.com/jborean93/ansible-windows/blob/master/vagrant/Vagrantfile
require 'yaml'

inventory = YAML.load_file('inventory.yml')

vars = inventory['all']['vars']

Vagrant.configure("2") do |config|
  inventory['all']['hosts'].each do |host,details|
    config.vm.define host do |config|
      host_portion = details['ip'].split(/\./)[3].to_i
      config.vm.box = details['vagrant_box']
      config.vm.box_version = details['box_version'] if details.key?('box_version')
      # config.vm.box_check_update = false # we specifically set the version for most of them so it's stable
      config.vm.hostname = host
      # config.vbguest.auto_update = false # we can enable this later, but it just slows things down for now

      if details['box_type'] == 'linux'
        ansible_port = vars['vagrant_ports']['ssh']['host'] + host_portion
      else # default to windows hosts
        ansible_port = vars['vagrant_ports']['winrm_http']['host'] + host_portion
        # config.vm.guest = :windows # it was working fine without this, but might as well add it
        config.vm.communicator = "winrm"
        config.vm.boot_timeout = 600 # might need to increase this per issue 2... wasn't happening before though
        config.winrm.timeout = 600 # might need to remove/increase this per issue 2
        # config.winrm.basic_auth_only = true # we should be able to remove this
        config.winrm.retry_limit = 20 # not sure if this does anything, should be able to remove
      end

      config.vm.network :private_network, ip: details['ip']
      vars['vagrant_ports'].each do |protocol, details|
        config.vm.network :forwarded_port, guest: details['guest'], host: details['host'] + host_portion
      end

      config.vm.synced_folder '.', '/vagrant', disabled: true

      # it doesn't matter if we send extra variables for windows hosts to linux boxes
      config.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
          ansible_port: ansible_port,
          ansible_winrm_scheme: vars['ansible_winrm_scheme'],
          ansible_winrm_server_cert_validation: vars['ansible_winrm_server_cert_validation'],
          win_password: vars['win_domain_admin_pass'],
          windows_domain_controller_private_ip: inventory['all']['hosts']['dc01']['ip'],
          win_timezone: vars['win_timezone'],
          root_domain: vars['root_domain'],
          domain_name: vars['domain_name'],
          win_domain_admin: vars['win_domain_admin'],
          local_admin_password: vars['local_admin_password'],
          hostname: config.vm.hostname,
          ansible_winrm_operation_timeout_sec: 120,
          ansible_winrm_read_timeout_sec: 150,
        }
        ansible.playbook = "ansible/#{host}.yml"
        ansible.config_file = "ansible/ansible.cfg"
        ansible.compatibility_mode = "2.0"
      end

      config.vm.provider :virtualbox do |vb|
        vb.gui = true # always have a GUI
        vb.name = 'RedTeamAttackLab_' + host
        vb.customize ["modifyvm", :id, "--memory", details.key?('memory') ? details['memory']: vars['default_host']['memory']]
        vb.customize ["modifyvm", :id, "--cpus", details.key?('cpus') ? details['cpus']: vars['default_host']['cpus']]
        vb.customize ["modifyvm", :id, "--vram", "64"]
      end
    end
  end
end
```

Inventory.yml:

```
# based on https://github.com/jborean93/ansible-windows/blob/master/vagrant/inventory.yml
all:
  hosts:
    dc01:
      ip: 10.0.1.10
      vagrant_box: StefanScherer/windows_2019
      box_version: 2021.05.15
      box_type: windows
      linked_clone: true
      cpus: 2
      memory: 4096
    win2022-1:
      ip: 10.0.1.17
      vagrant_box: StefanScherer/windows_2022
      box_version: 2021.08.23
      box_type: windows
      linked_clone: true # even though there's one, it speeds up testing; this will be removed later
    win2019-adcs:
      ip: 10.0.1.14
      vagrant_box: StefanScherer/windows_2019
      box_version: 2021.05.15
      box_type: windows
      linked_clone: true
    win2019-1:
      ip: 10.0.1.15
      vagrant_box: StefanScherer/windows_2019
      box_version: 2021.05.15
      box_type: windows
      linked_clone: true
    win10-1:
      ip: 10.0.1.20
      vagrant_box: StefanScherer/windows_10
      box_version: 2021.12.09
      box_type: windows
      linked_clone: true
    win10-2:
      ip: 10.0.1.21
      vagrant_box: StefanScherer/windows_10
      box_version: 2021.08.17
      box_type: windows
      linked_clone: true
    win11-1:
      ip: 10.0.1.22
      vagrant_box: StefanScherer/windows_11
      box_version: 2021.12.09
      box_type: windows
      linked_clone: true # just in case we want to add another win11 host for testing
    win10-dev:
      ip: 10.0.1.25
      vagrant_box: StefanScherer/windows_10
      box_version: 2021.08.17
      box_type: windows
      linked_clone: true
    win7-1:
      ip: 10.0.1.23
      vagrant_box: d1vious/windows_7
      box_version: 1.0
      box_type: windows
      linked_clone: true # even though there's one, it speeds up testing; this will be removed later
    metasploitable3-win2k8:
      ip: 10.0.1.30
      vagrant_box: rapid7/metasploitable3-win2k8
      box_version: 0.1.0-weekly
      box_type: windows
    metasploitable3-ub1404:
      ip: 10.0.1.31
      vagrant_box: rapid7/metasploitable3-ub1404
      box_version: 0.1.12-weekly
      box_type: linux
    kali:
      ip: 10.0.1.88
      vagrant_box: kalilinux/rolling
      box_type: linux
      linked_clone: true # even though there's one, it speeds up testing; this will be removed later
      cpus: 2
      memory: 4096

  vars:
    root_domain: attacklab.local
    domain_name: attacklab
    tld: local # not used yet, placeholder in case we need it
    win_domain_admin: Administrator
    win_domain_admin_pass: P@ssw0rd
    local_admin_password: Windows2021 # not used yet
    win_timezone: Eastern Standard Time

    # ansible winrm config
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_scheme: http

    # these are default values for hosts, you can override them in the host-specific config above
    default_host:
      cpus: 2
      memory: 4096

    # each protocol and host have their own port forward
    # the starting IP range (in thousands) is the 'host' variable
    # we add the host portion of the IP address to this e.g. dc01: rdp port is 20010, winrm is 22010, etc
    # we are theoretically maxed at a single network since a .10 on one network would clash with a .10 on another
    vagrant_ports:
      rdp:
        guest: 3389
        host: 30000
      ssh:
        guest: 22
        host: 31000
      winrm_http:
        guest: 5985
        host: 32000
      winrm_https:
        guest: 5986
        host: 33000
      smb:
        guest: 445
        host: 34000
```

### Debug output

https://gist.github.com/jt0dd/01e3a0a379ecd348ed34a5f45f2d4429

### Expected behavior

Windows finishes booting

### Actual behavior

Windows guest host freezes

### Steps to reproduce

1. git clone https://github.com/Marshall-Hallenbeck/red_team_attack_lab
2. cd ./red_team_attack_lab
3. vagrant plugin install vagrant-hostmanager vagrant-vbguest
4. vagrant up

### References

Please see this issue: https://github.com/Marshall-Hallenbeck/red_team_attack_lab/issues/2

I tried tweaking the allocations for video memory, memory, cpu, etc. Couldn't get any output except this. The output doesn't seem helpful for diagnosing / debugging.
