### ISSUE TITLE
Replacing networkd with NetworkManager in vagrant

### ISSUE THREAD

**Issue by kimchitsigai** [hashicorp/vagrant#12805]
By default, vagrant seems to provision VMs with networkd as the netplan provider.
Is there a way to replace ```networkd``` with ```NetworkManager``` ?

My configuration is :
 - vagrant 2.2.19
 - virtualbox 6.1
 - generic/ubuntu2004

My Vagrantfile is:
```
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.define "master" do |master|
    master.vm.box = "generic/ubuntu2004"
  end
  config.vm.define "worker" do |worker|
    worker.vm.box = "generic/ubuntu2004"
  end
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
    vb.cpus = "3"
  end
end
```

50-vagrant.yaml on master is:
```
---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
```

01-netcfg.yaml on master is:
```
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: false
      optional: true
      nameservers:
        addresses: [4.2.2.1, 4.2.2.2, 208.67.220.220]
```

Thanks a lot,
Kimchi
