### ISSUE TITLE
Vagrant up failing and the end: Internal error. Invalid: virtiofs

### ISSUE THREAD

**Issue by JuanFelipeJaramillo20** [hashicorp/vagrant#13061]
I'm trying to set up an environment to use in my laptop with Vagrant, after using vagrant up, vagrant starts installing the box, but I keep getting this error:

```
raspaio_homestead: Successfully added box 'laravel/homestead' (v12.2.0) for 'virtualbox'!
Traceback (most recent call last):
	33: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	32: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/machine.rb:203:in `action'
	31: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/machine.rb:203:in `call'
	30: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/environment.rb:631:in `lock'
	29: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/machine.rb:217:in `block in action'
	28: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/machine.rb:248:in `action_raw'
	27: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `run'
	26: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/util/busy.rb:19:in `busy'
	25: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `block in run'
	24: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builder.rb:180:in `call'
	23: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
	22: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	21: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
	20: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	19: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `run'
	18: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/util/busy.rb:19:in `busy'
	17: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `block in run'
	16: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builder.rb:180:in `call'
	15: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
	14: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	13: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
	12: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	11: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
	10: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 9: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
	 8: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/config_validate.rb:15:in `call'
	 7: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/config/v2/root.rb:67:in `validate'
	 6: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/config/v2/root.rb:67:in `each'
	 5: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/config/v2/root.rb:72:in `block in validate'
	 4: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/kernel_v2/config/vm.rb:754:in `validate'
	 3: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/machine.rb:633:in `synced_folders'
	 2: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/mixin_synced_folders.rb:130:in `synced_folders'
	 1: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/mixin_synced_folders.rb:130:in `each'
/opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/mixin_synced_folders.rb:142:in `block in synced_folders': Internal error. Report this as a bug. Invalid: virtiofs (RuntimeError)
```

For context, I had to change the value of version in the homestead.rb script to this:

```
config.vm.box_version = settings['version'] ||= '>= 12.0.0, < 14.0.0'
```

Originally it was >= 13.0.0 but for some reason vagrant said that there were no versions that matched this restraint (even though clearly the version 13.0.0 matches the restraint)

And this is my homestead.yaml file:

```yaml
---
ip: "192.168.56.11"
name: "raspaio_homestead"
memory: 4024
cpus: 4
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /home/JJAR/Documents/TPI_PR/raspa-extension-api
      to: /home/vagrant/TPI_PR/raspa-extension-api

sites:
    #- map: local.raspaio.com
     # to: /home/vagrant/code/raspa.io/public
      #php: "7.4"
 
    - map: local.apiraspaio.com
      to: /home/vagrant/TPI_PR/raspa-extension-api/public
    
databases:
    - raspaio

ports:
     - send: 27017
       to: 27017
     - send: 3000
       to: 3000
     - send: 3306
       to: 3306

features:
    - mysql: false
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
    - mongodb: true

services:
    - enabled:
          - "mongod"
    - disabled:
       - "mysql"
```
