### ISSUE TITLE
Error when provisioning Vagrant with Ansible + SSH

### ISSUE THREAD

**Issue by jabclab** [hashicorp/vagrant#2092]
I'm attempting to provision my Vagrant VM using Ansible. The following task is not currently working:

``` yml
- name: make sure xxx is installed at a global level
  npm: name="git+ssh://git@github.com:jabclab/xxx.git"
       global=yes
       executable={{ npm_executable }}
  sudo: yes
  when: dev_install is defined # <-- only install if for a Vagrant VM
```

I see the following error in the terminal:

```
failed: [vagrant.xxx] => {"cmd": ["/usr/local/n/versions/0.10.17/bin/npm", "install", "--global", "git+ssh://git@github.com:jabclab/xxx.git"], "failed": true, "item": "", "rc": 1}
stderr: npm ERR! git clone git@github.com:jabclab/xxx.git.git Initialized empty Git repository in /root/.npm/_git-remotes/git-github-com-jabclab/xxx.git-git-9ebe6b30/
npm ERR! git clone git@github.com:jabclab/xxx.git
npm ERR! git clone git@github.com:jabclab/xxx.git Warning: Permanently added the RSA host key for IP address '204.232.175.90' to the list of known hosts.
npm ERR! git clone git@github.com:jabclab/xxx.git Permission denied (publickey).
npm ERR! git clone git@github.com:jabclab/xxx.git fatal: The remote end hung up unexpectedly
```

Executing the command described above works fine after `vagrant ssh`. I've seen #1307 but it still isn't working for me. I'm running:
- OS X 10.8.2
- Vagrant **1.2.7**
- Ansible **1.2.3**

This is using the CentOS 6.4 64bit box which can be found [here](http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box).

Thanks :-)
