### ISSUE TITLE
ansible provisioning error on vagrant up

### ISSUE THREAD

**Issue by tkellen** [hashicorp/vagrant#2299]
I'm using Vagrant 1.3.3.  This is my Vagrantfile

``` ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :private_network, ip: "192.168.11.11"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end
end
```

This is my simple testing playbook:

``` yml

---
- hosts: all
  tasks:
    - name: ensure ntpd is at the latest version
      yum: pkg=ntp state=latest
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
```

When I run `vagrant up` I get the following:

``` shell
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible provisioner:
* The following settings shouldn't exist: inventory_file
```

Any idea what is up here?  I'm relying on Vagrant to generate the inventory_file, that setting **doesn't** exist in my configuration.
