### ISSUE TITLE
SSH agent forwarding doesn't work within salt states

### ISSUE THREAD

**Issue by mtford90** [hashicorp/vagrant#3165]
e.g in my vagrant file:

```
config.ssh.forward_agent = true
```

and my salt state:

```
git+ssh://git@bitbucket.org/xxx/repo.git:
  git.latest:
    - rev: rest
    - target: /home/vagrant/src
```

Executing `git+ssh://git@bitbucket.org/xxx/repo.git` whilst within my instance works fine, so I don't think I've configured ssh incorrectly.

Also, this works with neither the initial highstate nor with a manual `salt-call state.sls` post-provisioning.

Am I missing something else? Is this supposed to work? 

```
$ vagrant -v
Vagrant 1.5.0
```
