### ISSUE TITLE
Laravel site cannot be accessed by domain but can be by LocalHost:8000

### ISSUE THREAD

**Issue by TotiCuervo** [hashicorp/vagrant#9413]
I am fairly new to web programming and have come into a tough problem. In the past I would be able to access a larvel site by running the command "vagrant up" in the homestead folder and then using the site name that I indicated in the "Homestead.yaml" file.

Recently I updated my Mac to the latest version of High Sierra. I do not know if this is the main culprit, but for some reason now I am unable to reach the site by using the domain. I am however able to reach the laravel home page by going to localhost:8000.

here is a list of things that I have done trying to fix the issue:
I have tried uninstalling virtual box, homestead, and vagrant and reinstalling them but that has not fixed the issue.
I tried running vagrant -provisions but that did not help the situation
Here are my files:

Homestead.yaml

```
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: hoomestead1.app
      to: /home/vagrant/Code/Project1/public
    - map: lxa.app
      to: /home/vagrant/Code/lxa/public
    - map: beerstreet.app
      to: /home/vagrant/Code/beerstreet/public
    - map: blackbook.app
      to: /home/vagrant/Code/blackbook/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

Host Files

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost

192.168.10.10  homestead.app
192.168.10.10  hoomestead1.app
192.168.10.10  lxa.app
192.168.10.10  beerstreet.app
192.168.10.10  blackbook.app
```

I really have no clue what the problem could be. It was working fine a day ago and now will not work. Can anyone please give me a suggestion on things I haven't tried yet and should?
