### ISSUE TITLE
Vagrant up not working: Remote connection disconnect. Retrying...

### ISSUE THREAD

**Issue by rmertens** [hashicorp/vagrant#9416]
### Vagrant version
Vagrant 2.0.2

### Host operating system
macOS High Sierra 10.13.2

### Guest operating system
ubuntu/xenial64

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Box
  config.vm.box = "ubuntu/xenial64"

  # based on https://github.com/mitchellh/vagrant/issues/5186
  config.ssh.username = "ubuntu"

  # increase memory per https://www.vagrantup.com/docs/virtualbox/configuration.html
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  # Provision
  config.vm.provision :shell, :path => "vagrant-bootstrap.sh", binary: true

  config.vm.network "forwarded_port", guest: 80, host: 8004
  config.vm.network "forwarded_port", guest: 3306, host: 33306

  # Shared folders
  config.vm.synced_folder ".", "/var/admin"

end
```

### Debug output
https://gist.github.com/rmertens/a9cc66c8f53b61dd0642acd1a85fbdf0

### Expected behavior
We should be able to get a virtual machine and ssh into it.

### Actual behavior
```
    default: SSH address: 127.0.0.1:2222
    default: SSH username: ubuntu
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
```
Then when I try `vagrant ssh`, I get:
```
ubuntu@127.0.0.1: Permission denied (publickey).
```

### Steps to reproduce
1. vagrant up

### References
/

**Comment by Bennit** [comment]
Confirmed on linux - ubuntu 17.10
SSH key doesn't seem to be properly installed onto the guest OS - the machine is properly running according to virtualbox. Did not see any weird stuff on startup.
I tried falling back to older boxes - no change. Hard to switch back to vagrant 1.9 because that requires an older version of virtualbox which is not compatible with vagrant 2+.

**Comment by chrisroberts** [comment]
The underlying issue is just an authentication problem. I just pulled this box and `vagrant up`d it without issue. My guess is that you no longer need to define the `username` in your Vagrantfile. Please try removing that option and see if it will up the guest correctly.

Cheers!

**Comment by rmertens** [comment]
That solved it for me! Thanks @chrisroberts. For the record here's the output:
```
    default: SSH address: 127.0.0.1:2201
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
```
